// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: GameProtocol.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Google.Protobuf.GameProtocol {

  /// <summary>Holder for reflection information generated from GameProtocol.proto</summary>
  public static partial class GameProtocolReflection {

    #region Descriptor
    /// <summary>File descriptor for GameProtocol.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GameProtocolReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJHYW1lUHJvdG9jb2wucHJvdG8SCFByb3RvY29sGhNVbml0eVByb3RvY29s",
            "LnByb3RvIoABCgZQX1VuaXQSHgoDam9iGAEgASgOMhEuUHJvdG9jb2wuSm9i",
            "VHlwZRIqCglzdGF0ZVR5cGUYAiABKA4yFy5Qcm90b2NvbC5Vbml0U3RhdGVU",
            "eXBlEioKCmdhbWVPYmplY3QYAyABKAsyFi5Qcm90b2NvbC5QX0dhbWVPYmpl",
            "Y3QqMAoIUm9vbVR5cGUSCgoGUl9OT05FEAASCwoHUl9MT0JCWRABEgsKB1Jf",
            "RklFTEQQAipXCgdKb2JUeXBlEgwKCEpPQl9OT05FEAASEAoMUElTVE9MTUFT",
            "VEVSEAESEQoNTUFDSElORUdVTk5FUhACEgoKBlRBTktFUhADEg0KCVBPVElP",
            "TklTVBAEKpMBCg1Vbml0U3RhdGVUeXBlEg4KClNUQVRFX05PTkUQABIOCgpT",
            "VEFURV9JRExFEAESDQoJU1RBVEVfUlVOEAISDgoKU1RBVEVfV0FMSxADEg4K",
            "ClNUQVRFX0pVTVAQBBIPCgtTVEFURV9ET0RHRRAFEhAKDFNUQVRFX1JFTE9B",
            "RBAGEhAKDFNUQVRFX0FUVEFDSxAHQh+qAhxHb29nbGUuUHJvdG9idWYuR2Ft",
            "ZVByb3RvY29sYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.UnityProtocol.UnityProtocolReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Google.Protobuf.GameProtocol.RoomType), typeof(global::Google.Protobuf.GameProtocol.JobType), typeof(global::Google.Protobuf.GameProtocol.UnitStateType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Protobuf.GameProtocol.P_Unit), global::Google.Protobuf.GameProtocol.P_Unit.Parser, new[]{ "Job", "StateType", "GameObject" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum RoomType {
    [pbr::OriginalName("R_NONE")] RNone = 0,
    [pbr::OriginalName("R_LOBBY")] RLobby = 1,
    [pbr::OriginalName("R_FIELD")] RField = 2,
  }

  public enum JobType {
    [pbr::OriginalName("JOB_NONE")] JobNone = 0,
    [pbr::OriginalName("PISTOLMASTER")] Pistolmaster = 1,
    [pbr::OriginalName("MACHINEGUNNER")] Machinegunner = 2,
    [pbr::OriginalName("TANKER")] Tanker = 3,
    [pbr::OriginalName("POTIONIST")] Potionist = 4,
  }

  public enum UnitStateType {
    [pbr::OriginalName("STATE_NONE")] StateNone = 0,
    [pbr::OriginalName("STATE_IDLE")] StateIdle = 1,
    [pbr::OriginalName("STATE_RUN")] StateRun = 2,
    [pbr::OriginalName("STATE_WALK")] StateWalk = 3,
    [pbr::OriginalName("STATE_JUMP")] StateJump = 4,
    [pbr::OriginalName("STATE_DODGE")] StateDodge = 5,
    [pbr::OriginalName("STATE_RELOAD")] StateReload = 6,
    [pbr::OriginalName("STATE_ATTACK")] StateAttack = 7,
  }

  #endregion

  #region Messages
  public sealed partial class P_Unit : pb::IMessage<P_Unit> {
    private static readonly pb::MessageParser<P_Unit> _parser = new pb::MessageParser<P_Unit>(() => new P_Unit());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<P_Unit> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Protobuf.GameProtocol.GameProtocolReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public P_Unit() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public P_Unit(P_Unit other) : this() {
      job_ = other.job_;
      stateType_ = other.stateType_;
      gameObject_ = other.gameObject_ != null ? other.gameObject_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public P_Unit Clone() {
      return new P_Unit(this);
    }

    /// <summary>Field number for the "job" field.</summary>
    public const int JobFieldNumber = 1;
    private global::Google.Protobuf.GameProtocol.JobType job_ = global::Google.Protobuf.GameProtocol.JobType.JobNone;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.GameProtocol.JobType Job {
      get { return job_; }
      set {
        job_ = value;
      }
    }

    /// <summary>Field number for the "stateType" field.</summary>
    public const int StateTypeFieldNumber = 2;
    private global::Google.Protobuf.GameProtocol.UnitStateType stateType_ = global::Google.Protobuf.GameProtocol.UnitStateType.StateNone;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.GameProtocol.UnitStateType StateType {
      get { return stateType_; }
      set {
        stateType_ = value;
      }
    }

    /// <summary>Field number for the "gameObject" field.</summary>
    public const int GameObjectFieldNumber = 3;
    private global::Google.Protobuf.UnityProtocol.P_GameObject gameObject_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.UnityProtocol.P_GameObject GameObject {
      get { return gameObject_; }
      set {
        gameObject_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as P_Unit);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(P_Unit other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Job != other.Job) return false;
      if (StateType != other.StateType) return false;
      if (!object.Equals(GameObject, other.GameObject)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Job != global::Google.Protobuf.GameProtocol.JobType.JobNone) hash ^= Job.GetHashCode();
      if (StateType != global::Google.Protobuf.GameProtocol.UnitStateType.StateNone) hash ^= StateType.GetHashCode();
      if (gameObject_ != null) hash ^= GameObject.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Job != global::Google.Protobuf.GameProtocol.JobType.JobNone) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Job);
      }
      if (StateType != global::Google.Protobuf.GameProtocol.UnitStateType.StateNone) {
        output.WriteRawTag(16);
        output.WriteEnum((int) StateType);
      }
      if (gameObject_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(GameObject);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Job != global::Google.Protobuf.GameProtocol.JobType.JobNone) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Job);
      }
      if (StateType != global::Google.Protobuf.GameProtocol.UnitStateType.StateNone) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) StateType);
      }
      if (gameObject_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(GameObject);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(P_Unit other) {
      if (other == null) {
        return;
      }
      if (other.Job != global::Google.Protobuf.GameProtocol.JobType.JobNone) {
        Job = other.Job;
      }
      if (other.StateType != global::Google.Protobuf.GameProtocol.UnitStateType.StateNone) {
        StateType = other.StateType;
      }
      if (other.gameObject_ != null) {
        if (gameObject_ == null) {
          GameObject = new global::Google.Protobuf.UnityProtocol.P_GameObject();
        }
        GameObject.MergeFrom(other.GameObject);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Job = (global::Google.Protobuf.GameProtocol.JobType) input.ReadEnum();
            break;
          }
          case 16: {
            StateType = (global::Google.Protobuf.GameProtocol.UnitStateType) input.ReadEnum();
            break;
          }
          case 26: {
            if (gameObject_ == null) {
              GameObject = new global::Google.Protobuf.UnityProtocol.P_GameObject();
            }
            input.ReadMessage(GameObject);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
