// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: GameProtocol.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Google.Protobuf.GameProtocol {

  /// <summary>Holder for reflection information generated from GameProtocol.proto</summary>
  public static partial class GameProtocolReflection {

    #region Descriptor
    /// <summary>File descriptor for GameProtocol.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GameProtocolReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJHYW1lUHJvdG9jb2wucHJvdG8SCFByb3RvY29sGhNVbml0eVByb3RvY29s",
            "LnByb3RvKjAKCFJvb21UeXBlEgoKBlJfTk9ORRAAEgsKB1JfTE9CQlkQARIL",
            "CgdSX0ZJRUxEEAJCH6oCHEdvb2dsZS5Qcm90b2J1Zi5HYW1lUHJvdG9jb2xi",
            "BnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.UnityProtocol.UnityProtocolReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Google.Protobuf.GameProtocol.RoomType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum RoomType {
    [pbr::OriginalName("R_NONE")] RNone = 0,
    [pbr::OriginalName("R_LOBBY")] RLobby = 1,
    [pbr::OriginalName("R_FIELD")] RField = 2,
  }

  #endregion

}

#endregion Designer generated code
