// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protocol.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Google.Protobuf.Protocol {

  /// <summary>Holder for reflection information generated from Protocol.proto</summary>
  public static partial class ProtocolReflection {

    #region Descriptor
    /// <summary>File descriptor for Protocol.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProtocolReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5Qcm90b2NvbC5wcm90bxIIUHJvdG9jb2waE1VuaXR5UHJvdG9jb2wucHJv",
            "dG8aEkdhbWVQcm90b2NvbC5wcm90byrBAgoFTXNnSWQSCwoHU19MT0dJThAA",
            "EgsKB0NfTE9HSU4QARILCgdTX0VSUk9SEAISEQoNU19FTlRFUl9MT0JCWRAK",
            "EhEKDVNfTEVBVkVfTE9CQlkQCxIRCg1DX0NSRUFURV9ST09NEAwSEQoNU19D",
            "UkVBVEVfUk9PTRANEhIKDkNfQ09OTkVDVF9ST09NEA4SEgoOU19DT05ORUNU",
            "X1JPT00QDxIQCgxDX0xFQVZFX1JPT00QEBIQCgxTX0xFQVZFX1JPT00QERIX",
            "ChNTX0RJU0NPTk5FQ1RfUExBWUVSEBISEAoMQ19FTlRFUl9HQU1FEGQSEAoM",
            "U19FTlRFUl9HQU1FEGUSEAoMU19MRUFWRV9HQU1FEGYSEwoOU19TUEFXTl9Q",
            "TEFZRVIQlwESFQoQU19ERVNQQVdOX1BMQVlFUhCYAUIbqgIYR29vZ2xlLlBy",
            "b3RvYnVmLlByb3RvY29sYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.UnityProtocol.UnityProtocolReflection.Descriptor, global::Google.Protobuf.GameProtocol.GameProtocolReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Google.Protobuf.Protocol.MsgId), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum MsgId {
    [pbr::OriginalName("S_LOGIN")] SLogin = 0,
    [pbr::OriginalName("C_LOGIN")] CLogin = 1,
    [pbr::OriginalName("S_ERROR")] SError = 2,
    [pbr::OriginalName("S_ENTER_LOBBY")] SEnterLobby = 10,
    [pbr::OriginalName("S_LEAVE_LOBBY")] SLeaveLobby = 11,
    [pbr::OriginalName("C_CREATE_ROOM")] CCreateRoom = 12,
    [pbr::OriginalName("S_CREATE_ROOM")] SCreateRoom = 13,
    [pbr::OriginalName("C_CONNECT_ROOM")] CConnectRoom = 14,
    [pbr::OriginalName("S_CONNECT_ROOM")] SConnectRoom = 15,
    [pbr::OriginalName("C_LEAVE_ROOM")] CLeaveRoom = 16,
    [pbr::OriginalName("S_LEAVE_ROOM")] SLeaveRoom = 17,
    [pbr::OriginalName("S_DISCONNECT_PLAYER")] SDisconnectPlayer = 18,
    [pbr::OriginalName("C_ENTER_GAME")] CEnterGame = 100,
    [pbr::OriginalName("S_ENTER_GAME")] SEnterGame = 101,
    [pbr::OriginalName("S_LEAVE_GAME")] SLeaveGame = 102,
    [pbr::OriginalName("S_SPAWN_PLAYER")] SSpawnPlayer = 151,
    [pbr::OriginalName("S_DESPAWN_PLAYER")] SDespawnPlayer = 152,
  }

  #endregion

}

#endregion Designer generated code
